### ISSUE TITLE
 Building a docker images encounter some error (envirnment: arm,ubuntu )

### ISSUE THREAD

**Issue by Andydufresneguohao** [amosbird/ldb_toolchain_gen#1]
Step 5/14 : RUN wget https://doris-thirdparty-repo.bj.bcebos.com/thirdparty/ldb_toolchain_gen-v0.4.sh     -q -O /tmp/ldb_toolchain_gen.sh     && sh /tmp/ldb_toolchain_gen.sh /var/local/ldb-toolchain/     && rm /tmp/ldb_toolchain_gen.sh
 ---> Running in 1805d086ad7b
bin/gcc: line 7: /var/local/ldb-toolchain/bin/gcc-11: cannot execute binary file
bin/gcc: line 7: /var/local/ldb-toolchain/bin/gcc-11: Success
Generated toolchain cannot compile a simple program.
Please file an issue at https://github.com/amosbird/ldb_toolchain_gen/issues with current setup information.
The command '/bin/sh -c wget https://doris-thirdparty-repo.bj.bcebos.com/thirdparty/ldb_toolchain_gen-v0.4.sh     -q -O /tmp/ldb_toolchain_gen.sh     && sh /tmp/ldb_toolchain_gen.sh /var/local/ldb-toolchain/     && rm /tmp/ldb_toolchain_gen.sh' returned a non-zero code: 1

**Comment by amosbird** [comment]
Currently only x86 architecture is supported.

**Comment by Andydufresneguohao** [comment]
Thanks
