### ISSUE TITLE
Upgrade clang-13 to clang-14

### ISSUE THREAD

**Issue by adonis0147** [amosbird/ldb_toolchain_gen#11]
Hi @amosbird , Clang 14 was released. Are there any plans for upgrading clang-13 to clang-14 ?

**Comment by amosbird** [comment]
Hi. There is already a branch for that purpose https://github.com/amosbird/ldb_toolchain_gen/tree/llvm-14 . It will be in the next release.

**Comment by adonis0147** [comment]
Hi @amosbird , thanks for the prompt reply. That's great to have it in the next release!
