### ISSUE TITLE
support on ubuntu 20.04

### ISSUE THREAD

**Issue by spaces-X** [amosbird/ldb_toolchain_gen#12]
i got an error like the followings in ubuntu 20.04.
```
# sh ldb_toolchain_gen.sh /PATH/TO/LDB_TOOLS
ldb_toolchain_gen.sh: 12: [[: not found
ldb_toolchain_gen.sh: 17: [[: not found
...
```
It is appreciated that if the ldb tools can be run in ubuntu 20.04.

**Comment by amosbird** [comment]
> ldb_toolchain_gen.sh: 12: [[: not found

The error indicates your env doesn't have a working bash. `[[` is not generally available in posix sh.

Please try to use `bash ldb_toolchain_gen.sh` instead of `sh ldb_toolchain_gen.sh`.
