### ISSUE TITLE
Need coverage related tools：llvm-cov & llvm-profdata

### ISSUE THREAD

**Issue by pingchunzhang** [amosbird/ldb_toolchain_gen#18]
HI， @amosbird 。 For the need to calculate coverage， we have a strong demand for llvm cov related coverage calculation tool。As far as I know, the newest ldb_toolchain_gen support clang15，Can the latest installation include llvm-cov-15 and llvm-profdata-15？

**Comment by amosbird** [comment]
Hi. Yes, these tools should be included.

**Comment by amosbird** [comment]
Added in v0.14.2 .
