### ISSUE TITLE
Tag 0.17 don't support aarch64

### ISSUE THREAD

**Issue by peter5232** [amosbird/ldb_toolchain_gen#26]
change ARCH=x86_64 to ARCH=aarch64 and docker build
![image](https://github.com/amosbird/ldb_toolchain_gen/assets/58766816/4aa46aa9-fd3f-4595-9ccd-f0e17f19294c)

**Comment by peter5232** [comment]
> change ARCH=x86_64 to ARCH=aarch64 and docker build ![image](https://user-images.githubusercontent.com/58766816/270912742-4aa46aa9-fd3f-4595-9ccd-f0e17f19294c.png)

The host is x86_64.

**Comment by amosbird** [comment]
The generator currently doesn't support cross-compilation. To generate the required toolchain, please use aach64 host.

**Comment by amosbird** [comment]
Aarch64 toolchain has been released in v0.21 .
