### ISSUE TITLE
run doris be   failed    be.out   found   /lib64/libc.so.6: version `GLIBC_2.18' not found

### ISSUE THREAD

**Issue by xinda77** [amosbird/ldb_toolchain_gen#28]
OS: centos 7.6
ldb_toolchain_gen: robin
doris version: 2.0.3

Compiling Doris with LDB was successful, but an error occurred when starting Doris be. The detailed error information is shown below

 start time: Wed Dec  6 19:22:15 CST 2023
INFO: java_cmd /usr/java/jdk1.8.0_181-cloudera/bin/java
INFO: jdk_version 8
/XXX/doris/be/lib/doris_be: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /XXX/doris/be/lib/doris_be)
/XXX/doris/be/lib/doris_be: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /XXX/doris/be/lib/doris_be)

**Comment by amosbird** [comment]
Please provide the output of `readelf -s --wide /path/to/doris_be| grep 'GLIBC' | sort -V -t @ -k2` .

**Comment by xinda77** [comment]
Because I am in a hurry to use it, I have already compiled it using an old version of the LDB tool. I haven't had a chance to use the command you provided to troubleshoot. Thank you. Can we set any parameters during compilation to avoid this issue
