### ISSUE TITLE
[Help] Request clang-16 upgrade for aarch64

### ISSUE THREAD

**Issue by xinyiZzz** [amosbird/ldb_toolchain_gen#32]
the last ldb_toolchain_gen for aarch64 only supports clang-15, but the latest Doris requires clang-16 compilation, request upgrad for aarch64, thanks!~
![image](https://github.com/amosbird/ldb_toolchain_gen/assets/13197424/b5f40d2e-6142-4da3-bf80-886cc318678b)

**Comment by xinyiZzz** [comment]
> I attempted to build a toolchain on an ARM VPS. It appears that the LLVM ARM upstream is broken for version 18.x. I will investigate this issue further at a later time.

thanks for your attention~

**Comment by amosbird** [comment]
I've published a new release with aarch64 toolchain, which contains LLVM-17.
