### ISSUE TITLE
Create a symbolic link for g++.

### ISSUE THREAD

**Issue by adonis0147** [amosbird/ldb_toolchain_gen#5]
I think that we should create a symbolic link for g++. 
In my development environment, meson can't find the correct g++ after I export `PATH` with the ldb toolchain.

**Comment by amosbird** [comment]
Which version do you use? IIRC, the `g++` wrapper is there in day one.

```
 ❯ ll /tmp/toolchain/bin/g++
.rwxr-xr-x 148 amos  7 Mar 14:50 /tmp/toolchain/bin/g++
```
